name: main

on:
  push:
    branches:
      - master
    paths-ignore:
      - ".github/workflows/docs.yml"
      - "docs/**"
  pull_request:
    branches:
      - master
    paths-ignore:
      - ".github/workflows/docs.yml"
      - "docs/**"

env:
  SUBLIME_TEXT_VERSION: "4"
  SUBLIME_TEXT_ARCH: x64
  PACKAGE: lsp_utils
  UNITTESTING_TAG: master

jobs:
  macOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      - run: echo "$HOME/Library/Python/3.7/bin" >> $GITHUB_PATH
      - run: curl --silent https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/ci.sh --output ci.sh
      - run: |
          sh ci.sh bootstrap
          sh ci.sh install_package_control
          subl --stay &
          sleep 8
          sh ci.sh run_tests
        name: Run UnitTesting tests

  Linux:
    runs-on: ubuntu-latest
    container: sublimetext/unittesting
    steps:
      - uses: actions/checkout@v1
      - run: sudo apt update
      - run: sudo apt install --no-install-recommends -y x11-xserver-utils python3-pip
      - run: sh -e /etc/init.d/xvfb start
      - run: curl -OL https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/github.sh
      - run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      - run: |
          PATH="$HOME/.local/bin:$PATH"
          sh github.sh bootstrap
          sh github.sh install_package_control
          sh github.sh run_tests
        name: Run UnitTesting tests

  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          path: lsp_utils
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: sudo apt update
      - run: sudo apt install --no-install-recommends -y x11-xserver-utils
      - run: pip3 install mypy==0.790 flake8==3.8.3 yapf==0.30.0 --user
      - run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      - run: ls -la
      - run: git clone https://github.com/sublimelsp/LSP.git && touch LSP/__init__.py
      - run: cd lsp_utils && mypy st3
      - run: cd lsp_utils && flake8 st3 tests
