name: main

on:
  push:
    branches:
      - master
    paths-ignore:
      - ".github/workflows/docs.yml"
      - "docs/**"
  pull_request:
    branches:
      - master
    paths-ignore:
      - ".github/workflows/docs.yml"
      - "docs/**"

env:
  SUBLIME_TEXT_ARCH: x64
  PACKAGE: lsp_utils
  UNITTESTING_TAG: master

jobs:
  macOS:
    runs-on: macos-latest
    strategy:
      matrix:
        ST_VERSION: ['3', '4']
    env:
      SUBLIME_TEXT_VERSION: ${{ matrix.ST_VERSION }}
    steps:
      - uses: actions/checkout@v1
      - run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      - run: echo "$HOME/Library/Python/3.7/bin" >> $GITHUB_PATH
      - run: curl --silent https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/ci.sh --output ci.sh
      - run: |
          sh ci.sh bootstrap true  # true == skip pacakge copy
          sh ci.sh install_package LSP main https://github.com/sublimelsp/LSP.git
          sh ci.sh install_package LSP-pyright master https://github.com/sublimelsp/LSP-pyright.git
          sh ci.sh install_package_control
          sh ci.sh copy_tested_package true  # true == overwrite existing package directory
          subl --stay &
          sleep 8
          sh ci.sh run_tests
        name: Run UnitTesting tests

  Linux:
    runs-on: ubuntu-latest
    container: sublimetext/unittesting
    strategy:
      matrix:
        ST_VERSION: ['3', '4']
    env:
      SUBLIME_TEXT_VERSION: ${{ matrix.ST_VERSION }}
    steps:
      - uses: actions/checkout@v1
      - run: sudo apt update
      - run: sudo apt install --no-install-recommends -y x11-xserver-utils python3-pip
      - run: sh -e /etc/init.d/xvfb start
      - run: curl -OL https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/github.sh
      - run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      - run: |
          PATH="$HOME/.local/bin:$PATH"
          sh github.sh bootstrap true  # true == skip pacakge copy
          sh github.sh install_package LSP main https://github.com/sublimelsp/LSP.git
          sh github.sh install_package LSP-pyright master https://github.com/sublimelsp/LSP-pyright.git
          sh github.sh install_package_control
          sh github.sh copy_tested_package true  # true == overwrite existing package directory
          sh github.sh run_tests
        name: Run UnitTesting tests

  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          path: lsp_utils
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: sudo apt update
      - run: sudo apt install --no-install-recommends -y x11-xserver-utils
      - run: pip3 install mypy==0.790 flake8==3.8.3 yapf==0.30.0 --user
      - run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      - run: cd .. && git clone https://github.com/sublimelsp/LSP.git && touch ./LSP/__init__.py
      - run: cd .. && git clone https://github.com/SublimeText/sublime_lib.git
      - run: mypy st3
      - run: flake8 st3 tests
