name: main

on:
  push:
    branches:
      - master
    paths-ignore:
      - ".github/workflows/docs.yml"
      - "docs/**"
  pull_request:
    branches:
      - master
    paths-ignore:
      - ".github/workflows/docs.yml"
      - "docs/**"

jobs:
  Unittesting:
    strategy:
      fail-fast: false
      matrix:
        sublime_text:
          - version: 3
            lsp_tag: 'st3'
          - version: 4
            lsp_tag: 'main'
        os: ["ubuntu-latest", "macOS-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/checkout@v2
      - uses: SublimeText/UnitTesting/actions/setup@v1
        with:
          sublime_text_version: ${{ matrix.sublime_text.version }}
          extra-packages: |
            sublimelsp/LSP@${{ matrix.sublime_text.lsp_tag }}
            sublimelsp/LSP-pyright
      - uses: SublimeText/UnitTesting/actions/run-tests@v1
        with:
          sublime_text_version: ${{ matrix.sublime_text.version }}

  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          path: lsp_utils
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: sudo apt update
      - run: sudo apt install --no-install-recommends -y x11-xserver-utils
      - run: pip3 install mypy==0.790 flake8==3.8.3 yapf==0.30.0 --user
      - run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      - run: cd .. && git clone https://github.com/sublimelsp/LSP.git && touch ./LSP/__init__.py
      - run: cd .. && git clone https://github.com/SublimeText/sublime_lib.git
      - run: mypy st3
      - run: flake8 st3 tests
