name: main

on:
  push:
    branches:
      - master
    paths-ignore:
      - ".github/workflows/docs.yml"
      - "docs/**"
  pull_request:
    branches:
      - master
    paths-ignore:
      - ".github/workflows/docs.yml"
      - "docs/**"

jobs:
  Unittesting:
    name: Unittesting (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macOS-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - uses: actions/checkout@v4
      - if: ${{ matrix.os == 'macOS-latest' }}
        run: brew unlink openssl
      - uses: SublimeText/UnitTesting/actions/setup@v1
        with:
          sublime-text-version: 4
          extra-packages: |
            sublimelsp/LSP@main
            sublimelsp/LSP-pyright@main
      - uses: SublimeText/UnitTesting/actions/run-tests@v1

  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: lsp_utils
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: |
          sudo apt update
          sudo apt install --no-install-recommends -y x11-xserver-utils
      - run: pip3 install mypy==1.6.0 flake8==5.0.4 pyright==1.1.331 --user
      - run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      - run: git clone https://github.com/sublimelsp/LSP.git
      - run: git clone https://github.com/SublimeText/sublime_lib.git
      - run: |
          cd lsp_utils
          mypy st3/lsp_utils
          flake8 st3/lsp_utils tests
          pyright st3/lsp_utils
