name: main

on:
  push:
    branches:
      - master
    paths-ignore:
      - ".github/workflows/docs.yml"
      - "docs/**"
  pull_request:
    branches:
      - master
    paths-ignore:
      - ".github/workflows/docs.yml"
      - "docs/**"

env:
  SUBLIME_TEXT_ARCH: x64
  PACKAGE: lsp_utils
  UNITTESTING_TAG: master

jobs:
  macOS:
    name: Tests (macOS, ST${{ matrix.sublime_text.version }})
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        sublime_text:
          - version: 3
            lsp_tag: 'st3'
          - version: 4
            lsp_tag: 'main'
    env:
      SUBLIME_TEXT_VERSION: ${{ matrix.sublime_text.version }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      - run: echo "$HOME/Library/Python/3.7/bin" >> $GITHUB_PATH
      - run: curl -OL https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/github.sh
      - run: |
          sh github.sh bootstrap true  # true == skip package copy
          sh github.sh install_package LSP ${{ matrix.sublime_text.lsp_tag }} https://github.com/sublimelsp/LSP.git
          sh github.sh install_package LSP-pyright master https://github.com/sublimelsp/LSP-pyright.git
          sh github.sh install_package_control
          sh github.sh copy_tested_package true  # true == overwrite existing package directory
          sh github.sh run_tests
      - uses: OrbitalOwen/desktop-screenshot-action@0.1
        with:
          file-name: desktop${{ matrix.sublime_text.version }}.jpg

  Linux:
    name: Tests (Linux, ST${{ matrix.sublime_text.version }})
    runs-on: ubuntu-latest
    container:
      image: sublimetext/unittesting
      options: --cap-add=NET_ADMIN
    strategy:
      matrix:
        sublime_text:
          - version: 3
            lsp_tag: 'st3'
          - version: 4
            lsp_tag: 'main'
    env:
      SUBLIME_TEXT_VERSION: ${{ matrix.sublime_text.version }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: sudo apt update
      - run: sudo apt install --no-install-recommends -y x11-xserver-utils python3-pip
      - run: sh -e /etc/init.d/xvfb start
      - run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      - run: curl -OL https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/github.sh
      - run: |
          PATH="$HOME/.local/bin:$PATH"
          sh github.sh bootstrap true  # true == skip package copy
          sh github.sh install_package LSP ${{ matrix.sublime_text.lsp_tag }} https://github.com/sublimelsp/LSP.git
          sh github.sh install_package LSP-pyright master https://github.com/sublimelsp/LSP-pyright.git
          sh github.sh install_package_control
          sh github.sh copy_tested_package true  # true == overwrite existing package directory
          sh github.sh run_tests

  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          path: lsp_utils
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: sudo apt update
      - run: sudo apt install --no-install-recommends -y x11-xserver-utils
      - run: pip3 install mypy==0.790 flake8==3.8.3 yapf==0.30.0 --user
      - run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      - run: cd .. && git clone https://github.com/sublimelsp/LSP.git && touch ./LSP/__init__.py
      - run: cd .. && git clone https://github.com/SublimeText/sublime_lib.git
      - run: mypy st3
      - run: flake8 st3 tests
